### ISSUE TITLE
Merge, no-conversion and tags

### ISSUE THREAD

**Issue by kour1er** [sandreas/m4b-tool#100]
I'm not sure if I'm doing something stupid but... I'm trying to merge books which are mp3 files. They have been tagged with the additional fields of Sort Artist and Year in addition to the normal Artist, Title and Album.

I'm using the Brew version of m4b-tool. I would like to merge without conversion as I just want a single file version of the audiobook without transcoding. I'm using m4b-tool like this:

`m4b-tool -vv --no-cache --no-conversion --force merge SourceBookDir --output-file=test.mp3`

This merges the mp3 files perfectly, creates the chapters per different file and copies across the Artist, Title and Album tags. However, it doesn't copy across the Sort Artist and Year tag. Is there anyway to accomplish this?

**Comment by sandreas** [comment]
Hey. Thanks for reporting. This might be a bug in `v0.4.2`. There are a lot of fixes in the latest pre-release... you could try it, but I will also try to reproduce the problem... I'm pretty sure that the sort tags are treated in a special way.

I'll take a look in the next days.

**Comment by kour1er** [comment]
Just to provide additional data, I tried the same procedure with build latest-45-ga9b4ef7 and I got the same result. i.e. Artist, Title and Album tags copied fine, but Sort Artist and Year tag were not. 

Please let me know if I can provide any additional information

**Comment by sandreas** [comment]
Ok, some progress... 
- The date tag is indeed a problem, if only a year is provided (e.g. 2008), the date is not read out correctly
- The source tags are read out correctly, writing also works but somehow the tags are not displayed in iTunes, although they are present using `ffprobe`

Could you provide more information about your workflow? (e.g. which tools/software are you using to check the tags?)

**Comment by kour1er** [comment]
Thanks so much for looking into this @sandreas really appreciate it. 

I'm using [Meta](https://www.nightbirdsevolve.com/meta/) on macOS. Is there another tool you would recommend? 

- Date tag - yes I was only putting in the year i.e. 2008 as you thought

- When I look with ffprobe, I see that the date that I'm expecting is there on the merged file but the tag has been changed from 'date' to 'year'. I wonder if that's the issue?

- Sort Artist doesn't appear to show in ffprobe after the merge so that one looks like it really isn't copying. If I ffprobe a single mp3 file before merge, I can correctly see the 'artist-sort' show with the correct value I set in Meta, but not with the merged file.

**Comment by sandreas** [comment]
> I'm using Meta on macOS. Is there another tool you would recommend?

I'm don't know, which is the **best** tagging tool around and since i don't use `mp3` for anything except fixing bugs, i can't tell you which you should use. I made good experiences with **Mp3Tag** for windows, which could also be used with **Wine** on MacOS and Linux. 

Recently i heard about **Yate** but i did not test it...




At least I think i found out the reason for your problem:

- `date` and `year` are treated different by `ffmpeg`, and `m4b-tool` converts `year` into a valid `date` - this has to be changed / fixed
- `sort-title` (and other sort tags) are only supported in `id3v2.4` (not in `id3v2.3` which is used by default), so its likely that your source-file contains `id3v2.4` and the destination `id3v2.3` - here i will introduce a new parameter to change the id3 version if required, but this will take some time to find the right way for this
- `ffmpeg` does not seem to be the best tagging tool, so on the long term i will add a new dependency to fix the issues with this

What you could try as workaround is to add `--ffmpeg-param id3v2_version --ffmpeg-param ID3v2.4`to `m4b-tool` but this is pretty unlikely to work :-)

References:
- https://www.ffmpeg.org/ffmpeg-formats.html#mp3 (see parameter `id3v2_version`)
- https://wiki.multimedia.cx/index.php/FFmpeg_Metadata#MP3 (see `album-sort`)
- https://github.com/Martchus/tageditor (a potential new tag editor)
- https://wiki.archlinux.org/index.php/List_of_applications/Multimedia#Audio_tag_editors (other command line tag editors)

**Comment by kour1er** [comment]
Thanks for the incredibly detailed answer! 

I've emailed the developer of Meta to see what their thoughts on the whole date/year thing is so I will update if/when I hear back.

Adding the --ffmpeg-param option does indeed help. I'm in the middle of writing a wrapping python script for batch processing, calling out to m4b-tool and was looking at mutagen within this to inspect the tagging situation. With the ffmpeg--param options you detail above, mutagen sees the year tag as 

`TXXX=year=2020/10/07`

Which appears to confuse iTunes(Music.app) and Meta. If I re-add the original year tag, via mutagen, from one of the original mp3s

`audio.add(TDRC(encode=3, text=orig_year))`

after merging with m4b-tool, iTunes and Meta seem more happy. I know that is a workaround but.. :)

**Comment by sandreas** [comment]
> `TXXX=year=2020/10/07`

Yeah, this is exactly the date / year problem, which I'm going to fix in the next days (I already have an idea, how that might be done). 

And i will experiment with the `-id3v2_version` thing as well as the PHP Media lib (https://github.com/wapmorgan/MediaFile)... If I get it to work with one of these, i won't add a new dependency.

Thank you for your support and detailed testing feedback.

**Comment by sandreas** [comment]
Ok, the last commit should fix most of the problems, but I'm still experimenting with the tagging stuff... next build contains the fixes.

**Comment by sandreas** [comment]
It was indeed the `id3v2.4` version thing - no additional flags required du to the fact that checking for sort options will auto-activate the correct version of id3 writing. Same for date, this issue is fixed in the next pre-release.
