### ISSUE TITLE
Feature Request - Maybe a progress bar? 

### ISSUE THREAD

**Issue by adalovebang** [sandreas/m4b-tool#101]
Just that, or something to indication time to completion.

**Comment by sandreas** [comment]
Hello and thanks this feature request. I already thought about adding a progress indicator and it already partly is in the code, see https://github.com/sandreas/m4b-tool/blob/a8e63c30cf5d16d9a56e14336a7b4dc439c151b7/src/library/Executables/Tasks/Pool.php#L44

The problem is, that since `m4b-tool` is running parallel tasks and relying on third party tools (`ffmpeg`, `mp4v2` and `fdkaac` for conversion), the actual time / progress calculation is very inaccurate and for the whole progress of batch processing the calculation wouldn't even work at all... so having this information would be great, but it is tricky to calculate. 

I'll take a look at this again and keep the issue up to date :-)

**Comment by sandreas** [comment]
I did some improvements in Batch-Mode, that shows at least the remaining count of the jobs and some other useful information. Since the time calc is too much work for too little result, I would only reopen this, if there are at least 5 votes from other users. BUT keep in mind: Every hour I spend for this will not be spent in other features! I'm so sorry and I hope you are partially happy with the counting improvements
