### ISSUE TITLE
chapters derived from silence

### ISSUE THREAD

**Issue by dmaglio** [sandreas/m4b-tool#116]
to generate the chapters starting from the silence inside the audio track do I necessarily have to insert a text file of the type _chapters.txt_? my audiobooks in Italian don't exist on musicbrainz

**Comment by sandreas** [comment]
Well, unfortunately silence detection is not really useful for creating chapters out of nowhere. What `m4b-tool` automatically does: It creates a chapter for each track/file when merging multiple files. If you do not have more than one audio file and there is no other chapter information present (e.g. `id3` or `quicktime chapters`), silence detection won't help you that much, because normally there are way more silences in an audiobook, than only at chapters and often there is NO silence when a chapter starts.

So only way for such an audiobook without metadata is to create a chapters.txt manually, find another source for chapter information or create chapters of fixed lengths (e.g. every 5 minutes). If you would like to create a chapter every 5 minutes, you could adjust them via silence detection, but here's a little trick: If you use the latest pre-release, you maybe could use the `merge` command, to get that right...

```
m4b-tool merge --output-file book-with-chapters.m4b --max-chapter-length 300,900 --chapter-algo=grouping ./my-audiobook-input/
```

This **SHOULD** create an output file with a chapter every 5 minutes adjusted by silence (but maybe it will not work as expected, cause it is a pre-release and I'm still working on the new `--chapter-algo`).

**Comment by dmuiX** [comment]
Hello,

Its funny I just needed this functionality :D. And this command is working. Its just printing some weird warning, but the chapters and my audiobook are created. ```

PHP Warning:  file_put_contents(): Filename cannot be empty in phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php on line 226
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(): Filename cannot be empty
    [file] => phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php
    [line] => 226
)
```

**Comment by sandreas** [comment]
The above error should already be fixed in the next pre-release, so I'll close this ticket. Thanks for reporting.
