### ISSUE TITLE
Feature Request: support nero chapter format (formerly: Issues with playback of m4b files)

### ISSUE THREAD

**Issue by popcorn9499** [sandreas/m4b-tool#123]
I am currently running m4b-tool version `m4b-tool latest-51-gc64182b`

My issue is currently as follows and I really don't know who is exactly at fault here but anyways.
If I try to play the m4b files on my pc with vlc player or foobar or mpv they playback fine however, when I play these same files back on rockbox they refuse to play. 
Rockbox debug logs don't tell me much besides the fact that rockbox thinks it finished(or has no clue how to decode the file) and claims it finished playback the moment it starts playback. 

Some m4b files that I got before using m4b-tool worked fine however those were created 8 or so years ago. 
If I were to transcode the files with ffmpeg to aac then they playback correctly, also if I convert them back to m4b they work fine as well. 

I used this to convert them to aac and just changed file extensions to change back to m4b. 
`ffmpeg -i inputfile.m4b -acodec copy outputfile.aac`

Would you mind telling me maybe what ffmpeg commands you are using to generate these files and
if you don't mind giving me any insight in what I should be looking at to fix this it would be greatly appreciated.

Thank you

**Comment by popcorn9499** [comment]
Sorry to add something to this so quickly. Turns out even if I were to tell m4b-tool to output the merge of files to aac it creates the same issue when I used `--audio-format="aac"` however if i set it to mp3 using the same method it worked fine. Figured I would throw in my extra information that I discovered.

**Comment by sandreas** [comment]
Hey there. Thanks for reporting. This is something I noticed with ONE of my test-audiobooks. There was NOTHING I could do about and I did not find any reason, why that happened. The resulting audio file was much too long in iTunes and it also did not work there. 

It turned out, that the problem came from the source mp3 files and as i converted the source files to ogg / aac before merging, everything worked perfectly. So I think this is a problem with either `ffmpeg` or the combination of parameters, that `m4b-tool` uses.

I'm on it but to answer your question: You can use the `--debug` parameter, this will create a log file with all the `ffmpeg` commands and binary calls used.

**Comment by sandreas** [comment]
If you use the docker image, you could you try to add `--audio-profile=aac_he`. This fixes it in my case, because it is using another encoder (`fdkaac`) - so it is pretty likely that this is an `ffmpeg` specific issue.

**Comment by popcorn9499** [comment]
I will try today. thank you for getting back to me. I appologize for taking so long to get back to you with a response. University got in the way. anyways I will try to test this by the weekend or sooner.

**Comment by popcorn9499** [comment]
Well I learned what exactly it was that caused the problems with rockbox for me.  It ended up being mp4chaps. 

`'mp4chaps' '-i' '/tmp/m4b-tool/tmp_merged.m4b'` this exact line when ran on a file with the correct part of the chapters text file makes it unplayable however the regular ipod classic stock firmware could play it and vlc/itunes/foobar2000/mpv all could play it without issues. 

I guess I now have to look into why thats breaking

**Comment by sandreas** [comment]
Thanks for researching this - so I think, if this is a rockbox specific problem, it could be adressed by:

- Creating and issue at rockbox
- Using another tool for chapter-import

Tools, that are many tools able to import chapters, here's a short listing:
- `mp4chaps` from `mp4v2` - my preferred tool, because it is compatible with everything except rockbox ;-)
- `ffmpeg` - i would not use this, because it is inaccurate due to time formats and import issues (e.g. on `mp3`)
- `MP4box` - i never tried this one

**Comment by popcorn9499** [comment]
Thank you for your help and advice. mp4box seems to work. however I am gonna create an issue with rockbox and see if they will fix it since ideally even if rockbox doesn't support chapters in its user interface it doesnt crash when a file has chapters in it.

Have a great day!

Only last question would be. is it easy to just swap out mp4chaps with mp4box in m4b-tool?

**Comment by sandreas** [comment]
> is it easy to just swap out mp4chaps with mp4box in m4b-tool?

Not easy, but doable. Although this would be a feature request... If you don't mind I'll change this issue to `alternatively use mp4box for chapter import` ?!

You could also try to change the format of `mp4chaps` chapters (There are two: Nero Format and Quicktime Format)

**Comment by popcorn9499** [comment]
Decided to try something since you mentioned the two formats which I didn't realize I had much of an option in chapter formats. Anyways in trying that I learned the nero format works perfectly. I should test more but it seems to be the ideal format for my use case and rockbox doesn't crash. So should I make a new issue and close this one with that feature request? Or would you prefer renaming this issue here?
Either way doesn't bother me it's honestly what's easiest for you and if you even want to support this as a feature. 

Honestly wouldn't blame you if you didn't 

Anyways thank you again this has actually helped me alot. I learned alot because I really didn't know in the beginning of all of this the different chapter formats that existed or really much of anything in regards to aac besides its a audio codec.

**Comment by sandreas** [comment]
Changed to feature request...

**Comment by sandreas** [comment]
Should work with: `--use-nero-chapter-format`. Feedback welcome.
