### ISSUE TITLE
running silence detection for file takes too long -> memory leak, hgow to disable?

### ISSUE THREAD

**Issue by kmfstudio** [sandreas/m4b-tool#138]
running the latest pre-release on a mac. m4b-tool --version
m4b-tool latest-137-g14781fb

the process stuck at running "silence detection" which takes a long time. (it's a an audiobook with 1500 chapters and total size of 1.6 GB, 2170 minutes duration.
```

'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' '斗罗大陆IV终极斗罗-5-tmpfiles/tmp_斗罗大陆IV终极斗罗-5.m4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
'ffmpeg' '-hide_banner' '-i' '斗罗大陆IV终极斗罗-5-tmpfiles/tmp_斗罗大陆IV终极斗罗-5.m4b' '-af' 'silencedetect=noise=-30dB:d=0' '-f' 'null' '-'
running silence detection for file 斗罗大陆IV终极斗罗-5-tmpfiles/tmp_斗罗大陆IV终极斗罗-5.m4b with min length 00:00:00.000
silence detection finished
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20777131344 bytes) in phar:///usr/local/bin/m4b-tool/vendor/symfony/process/Process.php on line 685

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20777131344 bytes) in phar:///usr/local/bin/m4b-tool/vendor/symfony/process/Process.php on line 685
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 20777131344 bytes)
    [file] => phar:///usr/local/bin/m4b-tool/vendor/symfony/process/Process.php
    [line] => 685

```

is there an option to disable this? it doesn't seem that a chapter.txt is created like in docker prerelease on ubuntu.

**Comment by kmfstudio** [comment]
using a lower versiion has fixed this (m4b-tool --version
m4b-tool latest-97-ga6df141) (i tried this version because the memory leak bug was fixed around that time. _e

**Comment by sandreas** [comment]
Hey there,

thanks for reporting. It looks like the problem is not the silence detection itself, but more the value used for the minimum length of silences. Defaulting to `1750` (ms), the silence detection is pretty quick and the result usually is having only a few 100 items (or found silences) - even for very long audio books.

Decreasing the value too much will result in slower execution and  a vast amount of found silences. In your case it seems that the value has been set to `0`:

```
'silencedetect=noise=-30dB:d=0'
```

I'm not suprised that this is not going well. The question is: Did you provide the value as command line parameter (`--min-silence-length=0` trying to disable it or did `m4b-tool` use `0` as default value (which would indeed be a bug).

Could you please provide the complete command line command, you are using for further investigation?

**Comment by kmfstudio** [comment]
hello

i haven't changed the default. this is the command i use for all the conversions. i only change the book and author's name 

`m4b-tool merge --jobs=4 --writer="叶天南" --albumartist="叶天南" -album="超级医生"  --name="超级医生"  --output-file="超级医生-5.m4b" "www.piaotian.net/5" -vvv`

**Comment by sandreas** [comment]
Aaah I see... You are using `-album=...` not `--album=...`. Since `-a` is a shortcut for `--silence-min-length` this usage is not causing an error, but resulting in `--silence-min-length=lbum=超级医生`... Internally the value is cast to an integer without asking - resulting in `--silence-min-length=0`. 

I should definitely make this more robust, these kind of unwanted behaviour must be reported somehow. Thank you for finding this :-)

**Comment by kmfstudio** [comment]
ok, thanks for the explanation, i've just got the latedprerelease again and am trying it now with the correct -.
it sound logical, but not really obvious

**Comment by sandreas** [comment]
I'll keep this open, since I think there is definetely something to improve here.

**Comment by djdembeck** [comment]
Just chiming in to say I'd like to see an option to disable silence detection, as I create my own chapters :)

**Comment by sandreas** [comment]
Silence detection should not be executed, if there are already chapters present that are not too long, but I'll note that on my todo list 👍
