### ISSUE TITLE
Building docker container with podman creates the following error: make: *** [ffbuild/common.mak:60: libavcodec/vp8.o] Error 1

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#160]
When I try to build m4b-tool in podman it is throwing this error:

gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make: *** [ffbuild/common.mak:60: libavcodec/vp8.o] Error 1
make: *** Waiting for unfinished jobs....
Error: error building at STEP "RUN echo "---- INSTALL BUILD DEPENDENCIES ----"     && apk add --no-cache --update --upgrade --virtual=build-dependencies     autoconf     automake     boost-dev     build-base     gcc     lame-dev     libogg-dev     yasm     nasm     yasm-dev     zlib-dev     freetype-dev     libogg-dev     libtheora-dev     libvorbis-dev     openssl-dev     opus-dev     git     wget && echo "---- INSTALL RUNTIME PACKAGES ----"     && apk add --no-cache --update --upgrade bzip2     ca-certificates     coreutils     curl     file     libtool     freetype     lame     libogg     libvpx     libvorbis     libtheora     libvorbis     openssl     opus     pcre     php7-cli     php7-dom     php7-intl     php7-json     php7-xml     php7-curl     php7-mbstring     php7-simplexml     php7-phar     php7-openssl     php7-zip     pkgconf     pkgconfig     tar     && echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories     && apk add --update fdk-aac-dev     && echo "date.timezone = UTC" >> /etc/php7/php.ini && echo "---- COMPILE FFMPEG ----"     && cd /tmp/     && wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz     && tar zxf ffmpeg-${FFMPEG_VERSION}.tar.gz     && rm ffmpeg-${FFMPEG_VERSION}.tar.gz     && cd /tmp/ffmpeg-${FFMPEG_VERSION}     && ./configure     --enable-version3     --enable-gpl     --enable-nonfree     --enable-small     --enable-libmp3lame     --enable-libtheora     --enable-libvorbis     --enable-libopus     --enable-libfdk_aac     --enable-avresample     --enable-libfreetype     --enable-openssl     --disable-debug     --disable-doc     --disable-ffplay     --prefix="/tmp${PREFIX}"      --extra-cflags="-I/tmp${PREFIX}/include"     --extra-ldflags="-L/tmp${PREFIX}/lib"     --extra-libs="-lpthread -lm"     --bindir="/usr/local/bin/"      && make -j4 && make install && make distclean && hash -r && rm -rf /tmp/* && echo "---- COMPILE SANDREAS MP4V2 ----"     && cd /tmp/     && wget https://github.com/sandreas/mp4v2/archive/master.zip     && unzip master.zip     && rm master.zip     && cd mp4v2-master     && ./configure && make -j4 && make install && make distclean && rm -rf /tmp/* && echo "---- COMPILE FDKAAC ----"     && cd /tmp/     && wget https://github.com/nu774/fdkaac/archive/1.0.0.tar.gz     && tar xzf 1.0.0.tar.gz     && rm 1.0.0.tar.gz     && cd fdkaac-1.0.0     && autoreconf -i && ./configure && make -j4 && make install && rm -rf /tmp/* && echo "---- REMOVE BUILD DEPENDENCIES ----"     && apk del --purge build-dependencies": error while running runtime: exit status 2

**Comment by sandreas** [comment]
While podman is not officially supported, I think that I could do some improvements, as long as it takes not too much time. I'll take a look.

**Comment by sandreas** [comment]
Maybe the new *official*  docker image could solve your problems!? I would really appreciate if you could try it out... Let my cite my prepared announcement:

There is a new "official" (still experimental) docker multiarch image and *SHOULD* work on `x64`, and `Raspberry` platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
docker pull sandreas/m4b-tool:latest
```

In the near future, it will use tagging based on my new project [`tone`](https://github.com/sandreas/tone), which *SHOULD* be a huge improvement over the existing `mp4v2` and `ffmpeg` strategies. [The code is already commited](https://github.com/sandreas/m4b-tool/blob/master/src/library/Executables/Tone.php) and integrated in the docker image, but unfortunately there are some [*Known Issues*](https://github.com/sandreas/tone#known-issues), that prevent me from declaring `tone` as stable enough for production usage.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.
