### ISSUE TITLE
Building docker container for m4b-tool creates the following error: lstat /var/lib/docker/tmp/buildkit-mount024522595/dist: no such file or directory

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#161]
Building docker container for m4b-tool creates the following error: 
=> ERROR [3/5] ADD ./Dockerfile ./dist/m4b-tool.phar* /tmp/                                                                                                                                               0.3s
------
 > [3/5] ADD ./Dockerfile ./dist/m4b-tool.phar* /tmp/:
------
lstat /var/lib/docker/tmp/buildkit-mount024522595/dist: no such file or directory

**Comment by sandreas** [comment]
Well, the problem with this is, that the dockerfile is carefully structured. The line is important for the development process, but I will take a look as soon as possible. May take some time.

**Comment by sandreas** [comment]
Should be fixed. Feedback welcome.

**Comment by sandreas** [comment]
Maybe the new *official*  docker image could solve your problems!? I would really appreciate if you could try it out... Let my cite my prepared announcement:

There is a new "official" (still experimental) docker multiarch image and *SHOULD* work on `x64`, and `Raspberry` platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
docker pull sandreas/m4b-tool:latest
```

In the near future, it will use tagging based on my new project [`tone`](https://github.com/sandreas/tone), which *SHOULD* be a huge improvement over the existing `mp4v2` and `ffmpeg` strategies. [The code is already commited](https://github.com/sandreas/m4b-tool/blob/master/src/library/Executables/Tone.php) and integrated in the docker image, but unfortunately there are some [*Known Issues*](https://github.com/sandreas/tone#known-issues), that prevent me from declaring `tone` as stable enough for production usage.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.
