### ISSUE TITLE
Extra dependency in Ubuntu for PHP

### ISSUE THREAD

**Issue by wvhulle** [sandreas/m4b-tool#179]
php7.4-cli should be added as a dependency, otherwise php not found

**Comment by sandreas** [comment]
Could you give more details please? Where are you missing `php7.4-cli`?

**Comment by wvhulle** [comment]
I was trying the command-line version but this doesn't work without php, so you need to install php. Afterwards, it still doesn't work however. The docker version is not working for me since I get 

```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
```

**Comment by sandreas** [comment]
Well, we may have a misunderstanding here... The official instructions (`README.md`) state for Ubuntu:

```
# install all dependencies
sudo apt install ffmpeg mp4v2-utils fdkaac php-cli php-intl php-json php-mbstring php-xml
# ...
```

Which includes `php-cli`, so normally, everything should work as expected - and even more important: The documentation is up-to-date. If you are trying to say, that `php7.4-cli` is REQUIRED to make it work (instead of `php-cli`, I would need your exact Ubuntu-Version and as much info I could get about your system to trace this down.

> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

It seems like `docker` is not properly configured on your system. You could try to fix this by using `docker-ce` and add a group `docker` with permissions for your current `$USER`:
```
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository \
	   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	   $(lsb_release -cs) \
	   stable"
	
	sudo apt -y purge docker docker-engine docker.io
	sudo apt -y update
	sudo apt -y install docker-ce
	sudo groupadd docker
	sudo usermod -aG docker "$USER"
        sudo systemctl enable docker
        sudo systemctl start docker
```

**Comment by sandreas** [comment]
Closing due to no further feedback. Feel free to reopen, if necessary.
