### ISSUE TITLE
docker image fails to merge m4a files

### ISSUE THREAD

**Issue by jmgant** [sandreas/m4b-tool#183]
I am using the docker image. I have used the alias in the docs. the command is
`m4b-tool -vvv merge -f --jobs=8 --output-file=Bertrand/russell.m4b Bertrand/*`

the target directory is made of m4a files. this worked in the past, but for some reason the m4btool-bin package in the AUR doesn't work anymore.

It seems to be working fine until the end of the process when I get

`renaming cover /mnt/Bertrand/10-01 The age of Epicurus was a weary age..art[0].jpg => Bertrand/10-01 The age of Epicurus was a weary age..m4a/cover.jpg failed
preparing conversion with 6 simultaneous jobs, please wait...
   0 remaining /  350 total, preparing next task -
could not convert /mnt/Bertrand/description.txt to Bertrand/russell-tmpfiles/350-description-finished.m4b
trace: #0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(479): M4bTool\Command\MergeCommand->convertInputFiles()
#1 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(362): M4bTool\Command\MergeCommand->processInputFiles()
#2 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(194): M4bTool\Command\MergeCommand->processFiles()
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#4 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php(32): Symfony\Component\Console\Application->run()
#8 /usr/local/bin/m4b-tool(10): require('...')
#9 {main}
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => rename(/mnt/Bertrand/10-01 The age of Epicurus was a weary age..art[0].jpg,Bertrand/10-01 The age of Epicurus was a weary age..m4a/cover.jpg): Not a directory
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractConversionCommand.php
    [line] => 643
)`

I have tired both with and without a cover/description in the target dir.

any ideas for me?

**Comment by sandreas** [comment]
Maybe the new *official*  docker image could solve your problems!? I would really appreciate if you could try it out... Let my cite my prepared announcement:

There is a new "official" (still experimental) docker multiarch image and *SHOULD* work on `x64`, and `Raspberry` platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
docker pull sandreas/m4b-tool:latest
```

In the near future, it will use tagging based on my new project [`tone`](https://github.com/sandreas/tone), which *SHOULD* be a huge improvement over the existing `mp4v2` and `ffmpeg` strategies. [The code is already commited](https://github.com/sandreas/m4b-tool/blob/master/src/library/Executables/Tone.php) and integrated in the docker image, but unfortunately there are some [*Known Issues*](https://github.com/sandreas/tone#known-issues), that prevent me from declaring `tone` as stable enough for production usage.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.

**Comment by sandreas** [comment]
Closing due to no further feedback... feel free to reopen.
