### ISSUE TITLE
id3-tags as chapter-title

### ISSUE THREAD

**Issue by lduesing** [sandreas/m4b-tool#186]
Hi Andreas,
Thanks for your cool tool! 
I would prefer to use id3-tags as chapter-titles to the filenames on merge. There are no real constraints in id3-tags as opposed to file names.
Thanks again,

Lars

**Comment by sandreas** [comment]
> I would prefer to use id3-tags as chapter-titles to the filenames on merge. There are no real constraints in id3-tags as opposed to file names.

This *should* already be the default behaviour... since there is a `--use-filenames-as-chapters` parameter, which explicitely prefer the file NAMES over the tag titles, you should prevent using this...

Could you provide the complete command you are using and that does NOT work like expected? (like `m4b-tool mege --output-file=output.m4b input.mp3`)

**Comment by lduesing** [comment]
Ouch. Sorry. I used a sample command line without reading all. Error on my part. 
Thanks for the fast reaction!

**Comment by sandreas** [comment]
> I used a sample command line without reading all. Error on my part.
Thanks for the fast reaction!

You're welcome! Glad not having to fix something ;)
