### ISSUE TITLE
Question: How is bitrate/samplerate determined?

### ISSUE THREAD

**Issue by csandman** [sandreas/m4b-tool#193]
I've been looking through the code for a bit trying to determine how this package chooses the `audio-bitrate` and `audio-samplerate` options for a book if no defaults are passed, but I haven't had any luck (PHP really isn't my best langauge).  I did find [this mapping of samplerate to bitrate](https://github.com/sandreas/m4b-tool/blob/06c897dd4f91b770d0300c7bf3f267b6abe3f308/src/library/Command/AbstractConversionCommand.php#L74-L82) but I wasn't sure how that was applied.

I've been working on my own app recently which wraps this package, and noticed that certain files were getting converted down to 64k even when their original bitrate was over 120k and sample rate 44.1 kHz. I ended up making a mapping of my own, where I check whether the average bitrate of the audio files is within 10 of either 128k or 96k and using those if it is, but I was curious if your app had any motivation behind what it chooses or if it just defaults to 64k.  It could definitely influence my choices!

And thanks again for the amazing package, I get a ton of use out of it!

**Comment by sandreas** [comment]
> I've been looking through the code for a bit trying to determine how this package chooses the audio-bitrate and audio-samplerate options for a book if no defaults are passed

For generic defaults, see https://github.com/sandreas/m4b-tool/blob/ed1610812dda817ea9cd8c69d29adbb9dc92702e/src/library/Executables/AbstractFfmpegBasedExecutable.php#L53

For iPod adjustment, see https://github.com/sandreas/m4b-tool/blob/06c897dd4f91b770d0300c7bf3f267b6abe3f308/src/library/Command/AbstractConversionCommand.php#L167


Basically, 64k is the default, I personally use for all of my books. More is wasted, when using `libfdk_aac` in my opinion. I recommend you to specify your bitrate without having to much of an eye of the source material... the quality is not automatically better, when using better rates. If the source material was mp3 96k, then converted to 256k aac and then back to 128k aac, it is still max 96k mp3... 

Audio Quality is also very subjective... If you really wanna get out the last bits out of `m4b-tool`, you should choose `fdkaac` instead of `ffmpeg` (e.g. using `--audio-profile=aac_he`, when `fdkaac` is installed as command line tool or using the `docker` image).

**Comment by csandman** [comment]
Thanks for taking the time to respond!  Yeah, at the end of the day there may not be a huge gain from encoding above 64k, but at this point space isn't much of an issue for me.  I don't plan to ever go above 128k however.

> If the source material was mp3 96k, then converted to 256k aac and then back to 128k aac, it is still max 96k mp3...

And yes, I definitely agree with this!  I generally try to avoid transcoding as much as possible from the get-go, as every time you transcode to a lossy codec you lose quality regardless of settings (except when using filters to intentionally modify the audio).  I'm more just trying to avoid losing extra quality from say, an audiobook ripped from a CD, as I have noticed they sometimes sound better with higher bitrates.  I'll just have to hope none of my source files were transcoded to pointlessly high bitrates in the first place.  And like I said, I'm not overly concerned with space (storing these on a 120TB media server) so it doesn't really hurt to throw a little extra bitrate at my files.

---

Thanks for sharing your reasoning though, I will probably stick to the customization I made which uses the average bitrate of the source files to determine the output bitrate, but I might just end up leaving it on the default.  I'll have to think more about it!

**Comment by sandreas** [comment]
> Thanks for sharing your reasoning though, I will probably stick to the customization I made which uses the average bitrate of the source files to determine the output bitrate, but I might just end up leaving it on the default. I'll have to think more about it!

You're welcome. If you wanna find out the bitrate and samplerate of the source file, you might use the new `tone` release `0.0.8` with json format and audio stream info. 

Example: 
```
$ tone dump --format=json --query='$.audio' "a-file.m4b"

{
  "bitrate": 64,
  "format": "MPEG-4 Part 14",
  "formatShort": "MPEG-4",
  "sampleRate": 22050.0,
  "duration": 31614837.0,
  "vbr": true,
  "channels": {
    "count": 2,
    "description": "Stereo (2/0.0)"
  },
  "frames": {
    "offset": 39,
    "length": 252918342
  },
  "metaFormat": [
    "mp4"
  ]
}
```

**Comment by csandman** [comment]
No that's it, I'll close it!

And about tone, I was never able to get it to build on my M1 Mac.  I'd definitely be interested in trying it out if I could!
