### ISSUE TITLE
The process "'tone' 'tag' ... exceeded the timeout of 60 seconds."

### ISSUE THREAD

**Issue by djdembeck** [sandreas/m4b-tool#196]
Using latest pre-release. I haven't changed the way my command is formatted. How do I extend the timeout time?

```
M4B command: ['/usr/local/bin/m4b-tool', 'meta', '--ignore-source-tags', '/input/01 Apocalypse Cultivator.new.m4b', '--name=Apocalypse Cultivator - Warped Earth, Book 1', '--album=Apocalypse Cultivator', '--artist=Gabriel Michael, Katana Jones', '--albumartist=Jack Bryce', '--year=2022', '--description=I was doing well enough before the Apocalypse, but fast cars and penthouses mean nothing when the world changes into a wasteland filled with parasite-infested mutants. Now, the iron will that made me king of the boardroom is going to make me king of this new world....', '--series=Warped Earth', '--series-part=1', '--genre=Erotica/Science Fiction & Fantasy/Literature & Fiction/Romantic/Fantasy/Action & Adventure/Epic', '--comment=Unabridged', '--cover=/input/01 Apocalypse Cultivator.m4b_cover.jpg']
```
```
The process "'tone' 'tag' '--meta-cover-file' '/input/01 Apocalypse Cultivator.m4b_cover.jpg' '--meta-tone-json-file' '/tmp/tonePNphfM' '/input/01 Apocalypse Cultivator.new.m4b'" exceeded the timeout of 60 seconds.
Moving completed input /input/01 Apocalypse Cultivator.m4b to /input/done
Using chapter data from Audible
Applying chapters to m4b...
job begin: /output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b
Importing 23 QuickTime and Nero chapters from file /output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.chapters.txt into file "/output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b"
ReadAtom: "/output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b": invalid atom size, extends outside parent atom - skipping to end of "" "�~�" 2806795975 vs 382789636
closing /output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b
optimizing /output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b
ReadAtom: "/output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b": invalid atom size, extends outside parent atom - skipping to end of "" "�~�" 2806795975 vs 386995149
FindIntegerProperty: no such property - moov.mvhd.modificationTime (src/mp4file.cpp,831)
WARNING: optimize failed: /output/Jack Bryce/Apocalypse Cultivator/Apocalypse Cultivator - Warped Earth, Book 1.m4b
```

**Comment by sandreas** [comment]
> Using latest pre-release. I haven't changed the way my command is formatted. 

Latest pre-release checks for `tone` to be installed. If so, it tries to use `tone` to write tags, because it is more powerful than other tools (like `mp4v2`).

> How do I extend the timeout time?

Well, you can't (at least without changing `m4b-tool`'s code) - and you probably shouldn't. As you see here:

https://github.com/sandreas/m4b-tool/blob/69903d70562f98530f5a4ef4711a568a820e7dbc/src/library/Executables/Tone.php#L254

`tone` is executed with `$this->runProcess`, not with `$this->runProcessWithTimeout`. But the more interesting question is: Why does `tone` take so long on your system to write the metadata?

I can think of these possibilities:
- `tone` somehow stopped working or asks for confirmaton
- The audio files are on a pretty slow network share
- You are writing *huge* data (e.g. a big cover)

You could check the following solutions:

1. Uninstall or temporarily rename `tone` (e.g. to `tone2`), so that `m4b-tool` no longer tries to use it as tagging tool (that is only possible if you don't use `docker`)
2. Try to debug, what takes so long (try to run the `tone` command manually and see what's happening)

```bash
# keep in mind, that /tmp/tonePNphfM is a temporary file that maybe gets deleted
'tone' 'tag' '--meta-cover-file' '/input/01 Apocalypse Cultivator.m4b_cover.jpg' '--meta-tone-json-file' '/tmp/tonePNphfM' '/input/01 Apocalypse Cultivator.new.m4b'
```

Since this is a nasty bug, I'm willing to work with you, to find a solution for this. If you don't find a solution, I can either
- [ ] Add a flag or env-Variable `--please-dont-use-tone` (or similar)
- [ ] Change the `runProcess` to `runProcessWithTimeout` and respect a `M4BTOOL_PROCESS_TIMEOUT` environment variable

**Comment by djdembeck** [comment]
Thank you for the well-written reply! I set up everything again to reproduce this.

My best guess is Tone is re-encoding the file. I used `--debug`, which only provided a diff of the input vs. output (which I've linked below). According to `time`, `tone tag` took 1m 18.62s

https://pastebin.com/eSDLLM2h

**Comment by sandreas** [comment]
> My best guess is Tone is re-encoding the file.

This is pretty unlikely, because `tone` is not able to encode files... It seems that it takes REALLY long to write the tags here. My best guess is, that either you have slow IO (network drive or something is fishy with your hard drive) or something in the metadata causes a hickup in `tone`'s metadata routines.

> According to time, tone tag took 1m 18.62s.

Well, at least, it finishes. That means, a decent workaround would be to tell `m4b-tool` to use a timeout higher than 60 seconds.

So what I will do to fix this is:
- [ ] increase the default timeout to 120 seconds and make it editable via ENV variable
- [ ] an ENV variable to tell `m4b-tool` not to use tone for tagging
- [ ] try to find out what takes so long in `tone` and get rid of this problem

Thanks for reporting back.

**Comment by sandreas** [comment]
In the latest pre-release I introduced the following changes:

- `tone` default timeout is now 180 seconds
- two new env-variables to control timeout and `tone` usage (e.g. `M4B_TOOL_DISABLE_TONE=1` and `M4B_TOOL_PROCESS_TIMEOUT=300`)

Should also be fixed in docker image `sandreas/m4b-tool:latest`. 

Since this is a bigger change it might cause other issues, feedback is welcome. Feel free to reopen, if not fixed.

**Comment by sandreas** [comment]
> Would it be possible to expose some more debugging in tone to see which point it is taking so long? I feel that's the best course of action to narrow down the cause.

Sure, but this will take some time. Did the new `m4b-tool` version work? I'm not really happy with the latest one because #195 led to a huge slowdown in duration measuring, because `tone` seems also to be much slower in detecting duration than `mp4info`.

Seems that performance improvement is the next point on the todo list for `tone`.
