### ISSUE TITLE
Apple lossless codec 'alac' not working

### ISSUE THREAD

**Issue by mperkh** [sandreas/m4b-tool#20]
It would be nice, to be able to encode audio books into a lossless codec, so that its possible to make final lossy encode of the audio stream at a later time.

ffmpeg supports Apple lossless codec 'alac'. Trying to produce a result with a command like this:

`php ../m4b-tool.phar merge  --audio-codec="alac"  -d inputFolder --output-file="out.m4b"`

results in that:

```
...
In MergeCommand.php line 328:

  could not convert /Users/test/inputFile.m4a to out-tmpfiles/inputFile.m4b
```

Its seems the problem is caused by the `-f mp4` option, which is set on the final ffmpeg command, resulting in:

```
[mp4 @ 0x7ff18f00a400] Could not find tag for codec alac in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
```

Omitting the `-f mp4` option results in alac encoded m4a file to be correctly generated.

**Comment by sandreas** [comment]
Ok, thanks. I'll take a look in the next days :-)

**Comment by sandreas** [comment]
You were right...
Seems that ALAC is a bit tricky when using ffmpeg... since it was not officially mp4 compilant all the time (see: http://forum.doom9.org/archive/index.php/t-97014.html), ffmpeg complains when using alac in combination with -f mp4.

Should be fixed in current master, here is a build:
[m4b-tool.phar.zip](https://github.com/sandreas/m4b-tool/files/2706390/m4b-tool.phar.zip)
