### ISSUE TITLE
Allowed memory size exhausted - RuneList.php

### ISSUE THREAD

**Issue by kodirovshchik** [sandreas/m4b-tool#207]
Command:
`m4b-tool merge -vvv --jobs=8 --output-file="output/" --batch-pattern="input/%g/%a/%s/%p - %n/"  "input/" --no-chapter-reindexing`

Error: 
`==> trying improver ChaptersFromOverdrive 

'ffmpeg' '-hide_banner' '-i' 'input/Audiobook/Author/Series/01 - Series 01. Book 01/01-01.mp3' '-f' 'ffmetadata' '-'
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in phar:///usr/local/bin/m4b-tool-pre/vendor/sandreas/php-strings/src/Sandreas/Strings/RuneList.php on line 247
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes)
    [file] => phar:///usr/local/bin/m4b-tool-pre/vendor/sandreas/php-strings/src/Sandreas/Strings/RuneList.php
    [line] => 247
)`

Debian 11 Bullseye, m4b-tool latest-178-gaeb8b2b

[log.txt](https://github.com/sandreas/m4b-tool/files/10067911/log.txt)
[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/10068103/m4b-tool.log)

**Comment by sandreas** [comment]
Could you please run:

```bash
php -r 'echo ini_get("memory_limit");'
```

and provide the output of the command?

**Comment by kodirovshchik** [comment]
I don't have php installed. Does official docker image requires it? 
`~ $ whereis php

php:
`

**Comment by sandreas** [comment]
> I don't have php installed. Does official docker image requires it?

Ah, you are using `docker` - no then you don't need `php` installed on the host os, all dependencies are in the container.

It is pretty likely that you have HUGE metadata string in your audio file or something goes completely wrong. I have to investigate this further, but maybe I have to give you access to a private repo, so that you can provide the files where this is happening. 

May take a while, these `out of memory` stuff might be hard to solve. I try my best.

**Comment by kodirovshchik** [comment]
Ok. I figured it out a little. It's something with tags. After I removed and then returned the tags to their places, the book was successfully merged. I still have the original files. I can upload files somewhere, but it's 1.6 gigabytes.
