### ISSUE TITLE
Merge multiple m4b files without transcoding?

### ISSUE THREAD

**Issue by kristofferR** [sandreas/m4b-tool#23]
This seems to re-encode all the m4b files in the input folder, when I just want to merge them into a single m4b. 

Does an option to skip the unnecessary re-encoding exist or is that feature not implemented yet?

**Comment by sandreas** [comment]
Thanks for reporting... There is not explicetely an option for this, since i thought, ffmpeg would skip it automatically. As you might know, ffmpeg is used for merging files and `--audio-codec` parameter is more or less directly converted to ffmpegs `-acodec` parameter, so you could try to use:

```
--audio-codec="copy"
```

This might fail, i'm not sure, if this has side-effects - especially because ffmpeg should detect, if encoding is needed. I'm also not 100% sure, if there IS a merging capability in ffmpeg without re-encoding and whats the result, if you just copy the codec. 

BUT: I'll treat this issue as a feature request and will check the docs, so that you won't have to provide any parameter for just merging files as they are in the next version of m4b-tool - default option should be to copy the codec and not to transcode / encode again, when it is not neccessary.

**Comment by kristofferR** [comment]
The workaround I ended up using was CTRL-C after the first file was transcoded, then I just added the source files with the same file name structure (number-filename-finished.m4b) to the tmp folder. 

When I ran m4b-tool again it merged them into a single m4b without any transcoding or issues.

**Comment by sandreas** [comment]
Haha this is a nice one ;) But good that you mentioned it, perhaps i can provde a quickfix that way... i'll override the target files with the existing files and it should work...

thx

**Comment by sandreas** [comment]
Fixed by adding `--no-conversion` flag... feedback welcome, here is a build :-)
[m4b-tool.zip](https://github.com/sandreas/m4b-tool/files/2843087/m4b-tool.zip)

**Comment by gennaios** [comment]
Is it worth creating a new issue to track causes of failures when using `--no-conversion`? ffmpeg notes there could be multiple causes though I haven't looked into it. Using the latest version, plus AtomicParsley to first remove covers (somewhere someone mentioned that as a cause), I was able to get merging as such to properly work with correct chapters, though in one case metadata wasn't preserved and chapters were named by number. I haven't tried to track down what made it work. Should m4b-tool perform some steps such as removing covers or other metadata before attempting a merge as such?
