### ISSUE TITLE
Merged files with incorrect chapter marks if extension m4a is used

### ISSUE THREAD

**Issue by gennaios** [sandreas/m4b-tool#28]
I've yet to investigate what makes this happen but on one set of merged files, I have numerous instances of incorrect chapter marks.

In this case, the files are sourced from Audible. DRM removed losslessly. Their codec is AAC, around 62 kpbs bitrate, possibly constrained VBR but that's just a guess. I've heard VBR isn't recommended for podcasts since it can cause seeking problems. Unsure if that is a factor. Mp4chaps has an open pull request that might be related, unsure.

Opening up this issue before listing details and trying to find necessary info to document. Recommended steps? Without sharing files, maybe using some tool to list original file lengths and then chapters file from merge?

**Comment by sandreas** [comment]
Ok, thank you for reporting. I guess that it has something to do with the `--no-conversion` flag, which results in `ffmpeg` detecting the wrong track length for the files to merge (e.g. `1:37` instead of `1:35`). The more files, that are detected wrong, the higher the shift between chapter mark and real chapter position.

To debug this further, lets start with the basics: Please run the same command with the `--debug` flag and post:

- The full command you executed (e.g. `m4b-tool merge --debug my-audio-book/ -o merged.m4b`
- The command line output of the command
- The anonymized `m4b-tool_debug.log` (Please check for usernames etc.)

If you would like to contact me directly (please do not send the audiobook files for legal reasons, just for a start of easier communication!), the E-Mail 

`sandreas@2019.temporarily.de` 

is available for the next three days.

**Comment by gennaios** [comment]
Tried 4 of 20 merges with the same set of files so far and can't reproduce it; the new files are ok. Looking at last time thru command history, I had already upgraded `ffmpeg` to `--HEAD` w/new brew instructions, temp folder names differ, and I had used a version of m4b-tool zipped in an issue to `/usr/local/bin` without updating other files thru `brew` (necessary?). So the only meaningful difference I think is `m4b-tool` version, currently using newest 0.3.3.

I'll try remaking all files in the set over the next few days and get back to you. Unless you can think of something that might have caused itsuch as the edition of `m4b-tool` at the time.

**Comment by sandreas** [comment]
Strange... should be the `ffmpeg` changes, afaik i did not change anything in the chapter logic. Tell me, if you are satisfied, then I will close this bug.

**Comment by gennaios** [comment]
I think I figured it out. I had since then reorganized audiobooks on my notebook, and renamed the files to `.m4b`, previously many were imported thru iTunes and named `.m4a`. It's when I merge `.m4a` files that I see the problem. Will a debug log still help? Perhaps ffmpeg does something different in the case of such files, even though they are the same. Command was:

`merge * --no-conversion  --fix-mime-type --output-file="/Users/----/Desktop/temp/14.m4a"`

**Comment by sandreas** [comment]
Ah now i know... its indeed a bug. If the extension is `mp4` or `m4b`, the length detection is done via `mp4info` because it is more accurate. In all other cases `ffmpeg` is used.

It's in the file `AbstractCommand.php`, method `readDuration`. 

As you stated in another issue, the best option would be to read the codec of the file for deciding, how to handle it. I found a way, how this could be reliably done with `ffmpeg` and I'll try this in the next days.

**Comment by sandreas** [comment]
Ok, here is a small update on this... seems that this is a combination of problems in `ffmpeg` and `m4b-tool`. There might be a problem, that `ffmpeg` does not provide the exact times, but there definetely was another problem in `m4b-tool`, that I'm about to fix and which resulted in a complete rewrite of the time parsing mechanism (faster, more elegant and now an extra composer package `sandreas/php-time`).

`ffmpeg` usually prints time strings in this format: 
`10:00:01.433` for `10h, 0m, 1s and 433ms`

Well, if there is an amount of milliseconds below `100`, like this:
`10:00:01.080`
in some cases `ffmpeg` prints out:
`10:00:01.08`

This results in `m4b-tool` interpreting the `08` as `8ms` instead of `80ms`, which results in a shift of `72ms` in this case. To prevent this, I implemented a workaround, that forces `m4b-tool` to pad trailing zeros, so that `10:00:01.08` is rewritten into `10:00:01.080` and so results in the correct time value.

There are some more fixes to do and I'm working on a codec / format detection mechanism, that should improve a lot of things, but his is a very time consuming task, so it would take a while.

**Comment by gennaios** [comment]
Thank you. As I now know and use files as `m4b`, you can decide on the priority and if you wish to prefer new features. Sounds like `ffmpeg` can report incorrect times on any file; that's a good find. Possible resulting offsets perhaps minor but they can add up.

**Comment by sandreas** [comment]
Well, i think i did it. Some other improvements included. I attached a build for testing. Be careful, its a nightly build.

[m4b-tool.zip](https://github.com/sandreas/m4b-tool/files/2973315/m4b-tool.zip)
