### ISSUE TITLE
Metadata not written to mp3 files

### ISSUE THREAD

**Issue by gubler** [sandreas/m4b-tool#30]
I understand that the primary output for m4b-tool is m4b files, but the `merge` command does support mp3 output. When I try to merge a directory of already tagged mp3 files into a single mp3 file with chapters, I end up with an mp3 file with no tags (not even Artist, title, cover, etc.).

I have tried several variations, including defining output format, codec, `--no-convert`, `--mark-chapters`, etc. It appears that the tagging step is just skipped if the output format is mp3. I did a test build of a m4b file and it was properly tagged and chaptered.

If this tool doesn't support tagging output mp3s, I can completely understand, I just wanted to confirm I was not missing something.

**Comment by sandreas** [comment]
> but the merge command does support mp3 output

> I have tried several variations, including defining output format, codec, --no-convert, --mark-chapters, etc. It appears that the tagging step is just skipped if the output format is mp3

Yes, with the release 0.3.3 mp3 tagging is not supported yet, but I'm working on it. I did some research but i did not find a possibility to create an mp3 with chapters with `ffmpeg`. 

Since `m4b-tool` already has a lot of dependencies (`ffmpeg`, `mp4v2` and optionally `fdkaac`) i would only add a new dependency if it replaces an old one.

Here is the specification of id3-Chapters, perhaps there is something in native PHP that i could use:
http://id3.org/id3v2-chapters-1.0

Here is a nightly build with at least tagging support, but it may break some other things since i have not tested everything. Just give me feedback if you find an issue...

A list of planned features that are already included:
- Batch merging with multiple patterns (to merge more than one audio book at once, based on directory names for tags)
- Sort title support (for series that are not sorted alphabetically like harry potter)
- Tagging for mp3
- Many other minor fixes and code improvements

[m4b-tool.zip](https://github.com/sandreas/m4b-tool/files/3033594/m4b-tool.zip)

**Comment by gubler** [comment]
It looks like you can add chapters using ffmpeg directly, but I can only find [an example using a metadata file](https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687) and from what I can see in your code, you are writing all of the metadata via command line arguments (according to `AbstractConversionCommand`. The linked article references an mp4 file, but I dumped the metadata from a podcast episode with chapters and got a similar format (I have attached the metadata file).

[metadata.txt](https://github.com/sandreas/m4b-tool/files/3034496/metadata.txt)

I guess if the output file was an mp3 you could dump the metadata to a file (along with any chapter information) and then add the proper command line arguments to import it. I understand that would be a pain to do, however.

I've forked the repo and if you don't get to it before I do, I'll see if I can figure out how to do that myself. However, it will be a month or more before I can really dig into the code (April is a very busy month for me).

Thanks for the awesome tool!

**Comment by sandreas** [comment]
Ok, I'll take a look at it. It would be very helpful if you could provide a command line sample, what you really executed... e.g.:

`m4b-tool merge my-mp3-files --output-file=output.mp3`

**Comment by sandreas** [comment]
Ok, should be fixed. Well not only fixed, but also improved. MP3-Chapters might be supported (like in podcasts), but this is experimental and not verified totally for all files. Additionally, Sort-Order Names and Descriptions should be supported, too.

Unfortunately there is no way to preselect the "media type" as audiobook in iTunes for mp3 files. It seems that this attribute is not stored in the mp3 file itself, but in the  iTunes media library database after changing the type of a file. See https://community.mp3tag.de/t/permanently-change-mediatype-for-itunes/13895/5 for reference. 

Heres a nightly for testing, if you would like to: [m4b-tool.zip](https://github.com/sandreas/m4b-tool/files/3045302/m4b-tool.zip)

Feedback is welcome.

**Comment by gubler** [comment]
I will test this early next week - I won't have a chance until then.

But thank you very much for implementing this.

As far as I know, you are correct that there is no "Audiobook" tag for MP3s that iTunes will acknowledge.

**Comment by gubler** [comment]
Sorry for the delay - I finally got to test this today and it is working as expected for mp3 files and chapter data.

**Comment by sandreas** [comment]
Nice to hear that. Since you are the only one who reported this, i will not make a release version only for this, because i'm refactoring the code to make it more maintainable first. Other nice features are coming ;)
