### ISSUE TITLE
File order issues

### ISSUE THREAD

**Issue by Dekker500** [sandreas/m4b-tool#31]
As a general request, add input option for input file ordering.

More specifically, I am attempting to do something like the following:

`m4b-tool merge --mark-tracks "file 1" "file 2" "another file" --output-file out.m4b`

Now, the conversion and output are OK, and there are chapter marks in the output file, but...

1. Chapter ORDER is incorrect - it appears the tool uses ALPHABETICAL ordering ("another file" placed before "file 1")
2. Chapter NAME - Here the tool names the chapter using something like "01 - another file - finished", "02 - file 1 - finished", etc. Why is the "-finished" terminator being used?

For the input ORDER, as a minimum, it would be useful to have a flag to "preserve-order", meaning whatever the order of the input files on the command line, keep that order in the final file. I have tried to artificially put song/track numbers in the MP3s to force the order, but this seems to be ignored.

**Comment by sandreas** [comment]
>  it would be useful to have a flag to "preserve-order"
You are absolutely right. But instead of another flag like `--preserve-order`, i have a proposal. The file ordering is a bit complex, because `m4b-tool` reads directories recursive by default. But if ONLY files are provided and no directory is included, i would preserve order by default, without the need of providing an extra flag.

What do you think? If you are happy with this, i take a look into this in the next days...

**Comment by Dekker500** [comment]
Actually, I just thought of another wrinkle: Track numbers already embedded in the input files. 

I'm not at the PC to test, but I don't think so OSes guarantee the order of expansion when wildcards are provided as an argument. Perhaps the flag is simplest - Alpha, Track Number, As-provided.

I haven't used it with folders. Would each folder produce a seperate output, or are they all merged? If they are separate, the sitting should be per output file...

**Comment by sandreas** [comment]
At the moment, all input arguments are recursively loaded if directory and added if file, then merged and then sorted alphabetically... so if you provide the following:
```
a.mp3
c.mp3
b.mp3
```
the merged result would be:
```
a.mp3
b.mp3
c.mp3
```

If you use folders, all files of the folder are loaded and sorted... e.g.:

```
m4b-tool my-folder2 my-folder --output-file="testing.m4b"

# although my-folder2 comes as first argument, it would result in:
my-folder/001.mp3
my-folder/002.mp3
my-folder/003.mp3
# ...
my-folder2/001.mp3
my-folder2/002.mp3
my-folder2/003.mp3
```

I never thought of a use case, where files are not named and sorted like they should be merged, but as i said: You are right... i think i will rework the file loading algorithm and think over a sane default behaviour instead of having extra flags for sorting... I'll provide a proposal in the next days.

**Comment by sandreas** [comment]
Ok, should be fixed. Sorting is only applied for single directories... if you provide more than one input argument (no matter if directory or file) the order is retained. Here is a [nightly](https://github.com/sandreas/m4b-tool/files/3076238/m4b-tool.zip), would be nice if you could give some feedback...

**Comment by Dekker500** [comment]
Thanks for the prompt action!

Unfortunately I won't be able to test until Tues earliest - I'm not near the machine until then!

Will update when I do.
