### ISSUE TITLE
mp3 source files with title tag issue

### ISSUE THREAD

**Issue by kour1er** [sandreas/m4b-tool#34]
I'm trying to use m4b-tool to merge mp3 files to an m4b. The mp3 files definitely have the title tag set but when I merge, in the m4b I just get sequential numbering (1,2,3 etc).

I'm using:

m4b-tool merge audiobook_path --output-file=test.m4b

Am I missing something super obvious or does m4b-tool not work with mp3 tag data? - Thanks

**Comment by sandreas** [comment]
> Am I missing something super obvious or does m4b-tool not work with mp3 tag data? - Thanks

No this should work. I recently released `v.0.4.0` - I'm a bit unhappy with this release, because i did A LOT of changes, some breaking changes, but they were necessary to keep the code maintainable. 

Would you mind upgrading and check the issue with the new release? It should be gone...

**Comment by kour1er** [comment]
OK - so I made sure everything was up to date (this is on a Mac by the way - I installed as per the instructions via brew). Then downloaded the latest release, renamed the .phar checked the version (0.4.0) and tried to build the book again. 

Still getting just numbers for chapters I'm afraid :(

I then tried running the process again in debug mode to see if that was helpful and saw this bit:

tagging file test-tmpfiles//tmp_test.m4b with tag:
M4bTool\Audio\Tag Object
(
    [encoder] => m4b-tool
    [title] => Part - 01

so here, "[title] => Part -01" that is what I'm expecting to see for the first chapter title. So m4btool is reading it - something after that point is happening?

**Comment by sandreas** [comment]
Ah i see :-) Here `m4b-tool`'s magic is happening - and seems to be unwanted in your case. Well, I need to explain that a bit... 

Since i own a few audiobooks, where the chapters are similar as in your case. 

```
Chapter 1
Chapter 2
Chapter 3
...
```

I'm german, so the word `Chapter` is completely useless and if there aren't real chapter names, i thought why should `m4b-tool` keep this information. So i added the following logic:

- Strip all numbers from all chapter names
- Compare all chapter names
- If more than 75% of the chapters have the same name after stripping the numbers, just reindex the chapters, because they do not  contain any useful information

Well, if this is unwanted behaviour in your case, it seems, that i need to add a flag: `--keep-chapter-names` or something, to prevent *reindexing* if it is unwanted.

I think i could provide you a nightly with that option in the next days. 

To solve this problem without a flag, you could also do the following:

- After merging, `m4b-tool` puts a file `<mergedname>.chapters.txt` in your output directory
- Take this file, put it into the source directory as `chapters.txt` and rename the chapters to anything you want
- Then do the merge again - `m4b-tool` will take the chapters from this file

What do you think? Is the "Part -01" name really something you need?

**Comment by kour1er** [comment]
Ah your explanation makes total sense :)

I don't *really* need it, that's just how I've always done it (and I have a lot of books structured this way). If you had time to add the --keep-chapter-names idea it would be much appreciated but I totally understand if you consider it outside of scope

**Comment by sandreas** [comment]
>  If you had time to add the --keep-chapter-names idea it would be much appreciated

Was a simple task, so i did it... things added:
- `--no-chapter-reindexing` - will prevent automatic reindexing of similar chapters
- `--use-filenames-as-chapters` - will use the filenames (without extension) for chapter names instead of using the tag title or already given chapters of a file

[Downnload m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/3144320/m4b-tool.tar.gz)

**Comment by kour1er** [comment]
Brilliant! Have now tried the nightly on three books with the --no-chapter-reindexing and it worked perfectly. Thanks so much

**Comment by sandreas** [comment]
Nice :-) Glad I could help.
