### ISSUE TITLE
Fatal Error: Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#39]
I am trying to put chapters from musicbrainz in a m4b. 

**This is the command:**
m4b-tool chapters --merge-similar --first-chapter-offset 4000 --last-chapter-offset 3500 -m 969d83a3-e80c-4b47-895a-5b8a410836bd "/mnt/d/Download/Star Wars Erben des Imperiums Hörbuch (Band 1).m4b"

**And I am constantly getting this fatal error:**
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 177 and defined in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php:33
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(177): M4bTool\Chapter\ChapterMarker->guessChaptersBySilences(Array, Array, NULL)
#1 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(128): M4bTool\Command\ChaptersCommand->buildChapters(Array)
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command-> in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php on line 33
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Uncaught TypeError: Argument 3 passed to M4bTool\Chapter\ChapterMarker::guessChaptersBySilences() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 177 and defined in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php:33
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(177): M4bTool\Chapter\ChapterMarker->guessChaptersBySilences(Array, Array, NULL)
#1 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(128): M4bTool\Command\ChaptersCommand->buildChapters(Array)
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterMarker.php
    [line] => 33
)

I think it is very weird because this command is not using the guessChaptersBySilences() function. 

I am using Ubuntu in WSL on Windows 10. I've installed all dependencies, but I am using a customized ffmpeg with all non free codecs installed. Although this should not have any impact on this issue

Thanks for creating this wonderful wrapper :)

**Comment by sandreas** [comment]
Thanks for reporting, I'll take a look in the next days :-)

**Comment by sandreas** [comment]
Ok, after analysing this, let me tell you first, that i was not able to reproduce the bug on my system, although i used the same command that you used. 

But i at least have an idea of what could have gone wrong... 

> I think it is very weird because this command is not using the guessChaptersBySilences() function.

Well, that is not fully correct, since musicbrainz chapters are nearly never fully matching the silences in the audio file and the shift increases or decreases, the longer the duration of the file is. So the `chapters` command always performs a silence detection and tries to adjust the chapter position of the musicbrainz values. Within this silence detection there also is a length detection part, to boost performance and not having to detect the full length of the file with an extra command. And this length detection is failing in your case, which i suppose happens because of `ffmpeg`s duration output to be not in the expected format. Since i've rewritten the whole length detection, there may be a solution.

I created a custom build with extra detection and output - please try it with the following command:
```
m4b-tool chapters -v --merge-similar --first-chapter-offset 4000 --last-chapter-offset 3500 -m 969d83a3-e80c-4b47-895a-5b8a410836bd "/mnt/d/Download/Star Wars Erben des Imperiums Hörbuch (Band 1).m4b"
```
There should be an output line like...:
```
found %s musicbrainz chapters and %s silences within length %s
```
Best case szenario: Error is gone and it works ;)

[m4b-tool.zip](https://github.com/sandreas/m4b-tool/files/3513204/m4b-tool.zip)

**Comment by dmuiX** [comment]
Wow...it just worked. No errors. Thanks :).
When will you release it?

**Comment by sandreas** [comment]
Cool, i'm glad it works for you.

> When will you release it?

Since this is a _one man show freetime project_ unfortunately there is no such thing like _release management_ or _fixed release dates_. For the next release I plan to rework a few things and throw away duplicated code... therefore it will take some time, but as the version in the link above does not contain any other changes than fixing this issue, you can use it as "stable".

I'll commit the changes this week and mark the bug as fixed.
