### ISSUE TITLE
Problem with large mp3 input files when using the fdkaac profile

### ISSUE THREAD

**Issue by jeromeof** [sandreas/m4b-tool#46]
I found I needed to split very large mp3 files e.g. if it was great than 4 hours the fdkaac would fail and leave a very very large PCM tmp file around. To solve this I have been looking at splitting the large mp3 into smaller ones which seems to solve the problem - the smaller ones later get merged back into a single large m4b fine - its just the initial transcoding that seems to fail with fdkaac.

**Comment by sandreas** [comment]
Since `fdkaac` only supports specific codecs, its usage required a workaround creating a temporary file with `ffmpeg`, because i did not find a way making pipes (`|`) work with Process handling.

After reading the documentation again, i found a way and now a temporary file is not needed anymore - which not only should fix this bug, but improve merging performance A LOT!

Here's a nightly build, but beware since there is some major refactoring going on, there might be other things, that are broken:

[m4b-tool.tar.gz nightly build](https://github.com/sandreas/m4b-tool/files/3581064/m4b-tool.tar.gz)

Feedback is welcome!

**Comment by jeromeof** [comment]
Cool, I will give it a go over the weekend

**Comment by sandreas** [comment]
Ok, i did some further tests and in my opinion this one should be fixed. Feel free to reopen the issue if there is still something wrong with it.
