### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by MitchTalmadgeUofU** [sandreas/m4b-tool#5]
Just curious, is this tool multithreaded at all? Could it benefit from multithreading? I noticed that each m4b file when merging is created one at a time -- since I have 8 cores, could I potentially be creating 8 mb4 files at a time? Or is ffmpeg already multithreaded...

Curious to hear your thoughts.

**Comment by sandreas** [comment]
Since m4b-tool is a wrapper for ffmpeg (and other tools), i think multithreaded encoding is already used. But i will check that again and possibly implement the --threads argument of ffmpeg to be more flexible.

Todo:
- Verify, that multiple threads are used while encoding
- Passthrough the --threads option for ffmpeg to be more flexible

**Comment by sandreas** [comment]
Done:
- Ffmpeg uses multithreading by default
- Added --ffmpeg-threads parameter to be more flexible
