### ISSUE TITLE
Unable to generate chapters when merging files

### ISSUE THREAD

**Issue by pk49800** [sandreas/m4b-tool#54]
On my Win10 64bit Laptop with WSL,
I tried to use the following commad below to merge a set of m4a files in a folder  to generate a large m4b file but it did not contain any chapters.
![image](https://user-images.githubusercontent.com/36910388/66264056-e89a2080-e830-11e9-9c99-5d4eceba0b32.png)

 m4b-tool merge --no-conversion --use-filenames-as-chapters --no-chapter-reindexing --jobs=8 "./Harry Potter and the Goblet of Fire" --output-file="Harry Potter and the Goblet of Fire.m4b"

**Comment by sandreas** [comment]
Works for me with the latest code. Could you try the [pre-release](https://github.com/sandreas/m4b-tool/releases/tag/latest)?
Be careful, due to huge code changes some features may be broken and the changes may cause data loss. I'm working on automated tests to ensure all features are working correctly, but this will still take a while.

**Comment by pk49800** [comment]
The pre-release works! Thanks a lot!
