### ISSUE TITLE
Split mp3s into better chapters without re-encoding?

### ISSUE THREAD

**Issue by gazpachoking** [sandreas/m4b-tool#59]
Not sure if this is possible yet, but currently I have mp3 audiobooks split into files with long chapters. I like the ability to split chapters smartly on audio silences, but unfortunately my garmin watch doesn't recognize chapters in m4b files. Is there a way to split my mp3 audiobook into more (separate file) chapters without re-encoding anything? It seems like I could probably run merge with the chapter splitting options, then run split again, but I don't see a no-conversion flag for the split tool.

(awesome tool btw, I wish garmin handled the m4b chapters properly, I'd just convert everything with a normal merge if that was the case)

**Comment by sandreas** [comment]
Thanks... :-)

I understand what you are trying to achieve. 

- You have a bunch of mp3 files, that are splitted by chapters but *too long* for your purpose
- You would like to keep the files like they are, except splitting them into more files, to have *subchapters* 
- You would like to take advantage of  the `m4b-tool` auto adjusting feature to split *subchapters* by silence
- To do this in acceptable quality, you don't want to re-encode the files but just generate the chapters

This is an interesting Problem. Did you test, wether your *garmin* watch does support *mp3 chapters* - so you could merge to an mp3 instead of an m4b and still use a single file. `m4b-tool` also supports embedding chapters to mp3 files...

But I also would take this as feature request. If it is not too much effort, i could add the `--no-conversion` flag to the `split` command - which would be a nice improvement.

**Comment by gazpachoking** [comment]
Yep, sounds like you understand my goal exactly. 😃 

> Did you test, wether your _garmin_ watch does support _mp3 chapters_

Hmm, didn't even know that was a thing. I'll try that out.

> But I also would take this as feature request. If it is not too much effort, i could add the `--no-conversion` flag to the `split` command - which would be a nice improvement.

That sounds like it would work perfectly. 😄

Thanks!

**Comment by sandreas** [comment]
Should work with the latest pre-release.

See:
- Download: https://github.com/sandreas/m4b-tool/releases/tag/latest
- Instructions: https://github.com/sandreas/m4b-tool#installation

**Comment by akvadrako** [comment]
BTW, this is not documented in the README.

**Comment by sandreas** [comment]
> BTW, this is not documented in the README.

Yeah `m4b-tool` lacks a lot of docs at the moment. Nothing I'm proud of, but can't do much about it - time is short :-/
