### ISSUE TITLE
batch-pattern error not enough arguments (missing: "input")

### ISSUE THREAD

**Issue by git-no** [sandreas/m4b-tool#60]
merge with `--batch-pattern` quits with error  **Not enough arguments (missing: "input").** 

with a command like
```
m4b-tool merge --output-file="data/" --batch-pattern="input/%g/%w/%m"
```

A command like 
```
m4b-tool merge --output-file="data/" --batch-pattern="input/%g/%w/%m" "input/"
```
works quite a time and creates a output directory, but without a file (without a audiobook)

mp3 files are stored in a path like _input/Audiobooks/J. K. Rowling/The Casual Vacancy_ for example.

Without input directory but with batch-pattern the m4b-tool refuse to work (the input directory is already included in the batch-pattern).

**Comment by sandreas** [comment]
> merge with --batch-pattern quits with error Not enough arguments (missing: "input").

This is correct and intended. `--batch-pattern` is only a pattern to split the according input directory, so an input directory is still required for matching the `--batch-pattern`. 
Example:
- How would you recursively scan a directory, with only the batch pattern `input/%g/%w/%m`? It is not possible, because the batch pattern can include any string...
- Otherwise with a directory `input/` the filescan gives you a file listing, which can be matched with the `--batch-pattern`

> works quite a time and creates a output directory, but without a file (without a audiobook)

Please provide a trailing slash and prefer `%a` instead of `%w` and `%n` instead of `%m` to see if that is what you need - i think this is a documentation issue, `writer` is NOT `author` - `mp4v2` maps `writer` to `composer` - which is more common for `narrator` (the `mp4v2` tools do not contain good mappings for audiobooks - it is more for video)

I recommend using this structure:
```
--batch-pattern="input/%g/%a/%s/%p - %n/"  --batch-pattern="input/%g/%a/%n/"
```

**Comment by git-no** [comment]
Thank you very much. That helped, it works. 
I do use now a trailing slash in batch-pattern, an input directory and some of the pattern described by you.

Vielen Dank, werde es weiter ausprobieren. Arbeite mit Docker und es klappt gut.
Beste Grüße aus der Schweiz
