### ISSUE TITLE
merging m4bs not working on windows

### ISSUE THREAD

**Issue by Turtlefacee** [sandreas/m4b-tool#63]
im using the following command and all i get is this,
`m4b-tool.phar merge "C:\Users\Josiah\Music\Elantris\" --output-file="C:\Users\Josiah\Music\Elantris\merged.m4b"`
https://i.imgur.com/GfeuVBt.png

**Comment by sandreas** [comment]
Well, this seems to be a windows specific issue, where `m4b-tool.phar` cannot be executed directly via command line.

First you have to add `php.exe` to your `%Path%` variable ([howto](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)). 

**Solution 1**
Instead of 
```
m4b-tool.phar merge "C:\Users\Josiah\Music\Elantris\" --output-file="C:\Users\Josiah\Music\Elantris\merged.m4b"
```
run
```
php m4b-tool.phar merge "C:\Users\Josiah\Music\Elantris\" --output-file="C:\Users\Josiah\Music\Elantris\merged.m4b"
```

** Solution 2**
create a batch file `m4b-tool.bat` beneath `m4b-tool.phar` with the contents below and then also add this batch file to your `%Path%`. 
```
@echo OFF
:: in case DelayedExpansion is on and a path contains ! 
setlocal DISABLEDELAYEDEXPANSION
php "%~dp0m4b-tool.phar" %*
```
After this you should be able to run
```
m4b-tool merge "C:\Users\Josiah\Music\Elantris\" --output-file="C:\Users\Josiah\Music\Elantris\merged.m4b"
```
which is a bit shorter than the first solution, but also a bit more work to do :-)

Let me know if that helped.

**Comment by sandreas** [comment]
Well, the problem seems to be solved (at least I hope so). If not, feel free to reopen the ticket again.
