### ISSUE TITLE
Any plan to port this to Go?

### ISSUE THREAD

**Issue by gatozee** [sandreas/m4b-tool#80]
Very useful tool! I use it frequently to convert and backup my mp3 audiobooks. Any plan to port it to Go so it is easier to deploy?

**Comment by sandreas** [comment]
Yeah i planned it once... but unfortunately my time is very limited at the moment. All plans to implement features or porting it to go or rust are to much effort for me alone at the moment.

The problem is, that porting is not that useful, because you would still need `ffmpeg`, `mp4v2` and `fdkaac` as third party command line tools or at least as library (which would result in a full rewrite of the logic). So it would be great to have a tool in go without any dependencies but this is utopia, because you also would have to port `mp4v2` (which is not that much work) but `ffmpeg` is hard to replace :-)

**Comment by gatozee** [comment]
Understood.
