### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by littlejeem** [sandreas/m4b-tool#87]
Hi @sandreas 
Just wondered about donations, I'm not a wealthy person but I'm happy to chip in now and again when I use tools like this a lot but can't upkeep them myself.

I also wondered if you'd come across Brave as a browser it uses its own 'currency' that you earn from voluntarily watching ads etc. I'd be happy to donate these to you if you were set up...just a thought.

**Comment by sandreas** [comment]
Hi littlejeem,

this is awesome - thank you very much, I really appreciate that. I never thought `m4b-tool` would earn any reputation and I'm still surprised, how many people use it. You starred `m4b-tool` on github, so you already "donated" for the project in a way.

Since I'm in the lucky situation as a developer with a good income working for fun in my free time, i would not use donated money for myself, but I'll keep this issue open and think about some other projects, i could support with the donations from happy `m4b-tool` users.

Projects that come to my mind are:

- Mozilla DeepSpeech
- Wikipedia Foundation
- FFMPEG

I will think about it - thank you very very much.

**Comment by sandreas** [comment]
So, today I added GitHub sponsors to my profile. If you would like to donate money, this is the way... of course I won't keep the whole money for myself, but donating (at least a major part of it) it to projects I think are worthy. 

As soon as there is any income, I'm thinking about publishing a donation report every now and then on https://pilabor.com, if it is not taking too much time. 

Let's see how it goes. Thank you.

**Comment by littlejeem** [comment]
Yarsssssssss!!!! About time 🤣 i've owed you several pints for 3years now!

**Comment by sandreas** [comment]
> Yarsssssssss!!!! About time rofl i've owed you several pints for 3years now!

Hehe, don't feel pushed. I'm still experimenting with GH Sponsors and maybe I'll add a benefit (a private repo with extra documentation and tricks or helpful `tone` JavaScript plugins I created... :-) We'll see, this is a first test.

**Comment by sandreas** [comment]
@littlejeem Hey, thank you for your sponsorship. Enjoy the extra content in the private repository :-) Be sure to take a look at the special `m4b-tool` release, I think you will like it.
